default: &default
  adapter: postgresql
  encoding: unicode
  #host: localhost
  host: 35.226.239.37
  pool: 5
  username: postgres
  password: Wood1023

development: &development
  <<: *default
  database: postgres

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *development

preproduction:
  <<: *development

production:
  <<: *development

test:
  <<: *default
  database: consul_test
